apiVersion: v1
kind: Service
metadata:
  name: quarkus-app-service
spec:
  selector:
    app: quarkus-app
  ports:
    - protocol: TCP
      port: 18081
      targetPort: 8080
  type: NodePort
  